import { describe, expect, it } from 'vitest'

import vectorsJson from '../vectors.json?raw'

import { marshalAux, marshalCanonical } from '../../src/encoding.js'
import { hashBlock, signBlock } from '../../src/hash.js'
import { bytesToHex, hexToBytes } from '../../src/hex.js'
import { powHash } from '../../src/pow.js'
import { parseLossless } from '../../src/json.js'
import { toAddress, toHash, toPublicKey, type Address, type Asset, type Block, type Hash } from '../../src/types.js'
import { Wallet, verifySignature } from '../../src/wallet.js'

/**
 * Parity against the node.
 *
 * `test/vectors.json` is generated by the Go implementation itself, so these
 * are not assertions about what we think the format is — they are the node's
 * own output. If either side drifts, this file fails, which is the entire
 * point: a byte wrong here is a block the network rejects.
 */
interface Vector {
  name: string
  network_id: string
  seed_hex: string
  pub_key_hex: string
  address: string
  block: Record<string, unknown>
  canonical_hex: string
  aux_hex: string
  hash: string
  signature: string
}

interface PowVector {
  hash_hex: string
  nonce: string
  pow_hash: string
}

/**
 * Read the fixture with the SDK's own lossless parser.
 *
 * Plain JSON.parse rounds `timestamp` (~1.78e18) and any amount above 2^53,
 * which silently corrupts the very bytes these vectors exist to pin. The first
 * draft of this file used JSON.parse and every canonical-bytes assertion
 * failed — which is a fair demonstration of why `json.ts` exists at all.
 */
const fixture = parseLossless(vectorsJson) as {
  vectors: Vector[]
  pow_vectors: PowVector[]
  pow_difficulty: string
}

/** Rebuild the SDK's Block from the node's JSON wire form. */
function toBlock(raw: Record<string, unknown>): Block {
  const str = (k: string): string | undefined =>
    typeof raw[k] === 'string' ? (raw[k] as string) : undefined
  const num = (k: string): bigint | undefined =>
    raw[k] === undefined ? undefined : BigInt(raw[k] as string | number)

  const block: Block = {
    type: raw['type'] as Block['type'],
    account: toAddress(str('account')!),
    previous: (str('previous') === '0' ? '0' : toHash(str('previous')!)) as Hash | '0',
    balance: num('balance') ?? 0n,
    timestamp: num('timestamp') ?? 0n,
    asset: (str('asset') ?? 'XE') as Asset,
  }
  if (str('destination')) block.destination = toAddress(str('destination')!)
  const amount = num('amount')
  if (amount !== undefined) block.amount = amount
  if (str('source')) block.source = toHash(str('source')!)
  if (str('representative')) block.representative = toAddress(str('representative')!) as Address
  const memo = str('memo')
  if (memo !== undefined) block.memo = memo
  if (str('pub_key')) block.pubKey = toPublicKey(str('pub_key')!)
  const fields = [
    ['vcpus', 'vcpus'],
    ['memory_mb', 'memoryMb'],
    ['disk_gb', 'diskGb'],
    ['duration', 'duration'],
    ['locked_r', 'lockedR'],
    ['locked_payout_cap', 'lockedPayoutCap'],
    ['locked_twap_milli', 'lockedTwap'],
  ] as const
  for (const [wire, key] of fields) {
    const value = num(wire)
    if (value !== undefined) block[key] = value
  }
  if (str('access_pub_key')) block.accessPubKey = str('access_pub_key')!
  if (str('certificate_hash')) block.certificateHash = toHash(str('certificate_hash')!)
  if (Array.isArray(raw['attestations'])) {
    block.attestations = (raw['attestations'] as Record<string, unknown>[]).map((a) => ({
      publicKey: toPublicKey(a['public_key'] as string),
      timestamp: BigInt(a['timestamp'] as string | number | bigint),
      signature: a['signature'] as string,
    }))
  }
  return block
}

describe('block vectors from the node', () => {
  for (const v of fixture.vectors) {
    describe(`${v.name} @ ${v.network_id}`, () => {
      const block = toBlock(v.block)

      it('derives the same address from the seed', () => {
        expect(Wallet.fromSeedHex(v.seed_hex).address).toBe(v.address)
        expect(Wallet.fromSeedHex(v.seed_hex).publicKey).toBe(v.pub_key_hex)
      })

      it('encodes byte-identical canonical bytes', () => {
        expect(bytesToHex(marshalCanonical(block))).toBe(v.canonical_hex)
      })

      it('encodes byte-identical aux bytes', () => {
        expect(bytesToHex(marshalAux(block))).toBe(v.aux_hex)
      })

      it('produces the same hash', () => {
        expect(hashBlock(block, v.network_id)).toBe(v.hash)
      })

      it('produces the same signature', () => {
        const wallet = Wallet.fromSeedHex(v.seed_hex)
        const { previous: _p, ...rest } = block
        const signed = signBlock({ ...rest, previous: block.previous }, wallet, v.network_id)
        expect(signed.hash).toBe(v.hash)
        expect(signed.signature).toBe(v.signature)
      })

      it('verifies the node signature against the node hash', () => {
        expect(
          verifySignature(toPublicKey(v.pub_key_hex), hexToBytes(v.hash, 32), v.signature),
        ).toBe(true)
      })
    })
  }

  it('binds the network id into the hash, so a block cannot cross networks', () => {
    const byName = new Map<string, Vector[]>()
    for (const v of fixture.vectors) {
      byName.set(v.name, [...(byName.get(v.name) ?? []), v])
    }
    let compared = 0
    for (const [, group] of byName) {
      if (group.length < 2) continue
      const [a, b] = group as [Vector, Vector]
      expect(a.canonical_hex).toBe(b.canonical_hex) // same bytes …
      expect(a.hash).not.toBe(b.hash) // … different hash
      expect(a.signature).not.toBe(b.signature)
      compared++
    }
    expect(compared).toBeGreaterThan(0)
  })
})

describe('proof-of-work vectors from the node', () => {
  it('agrees on the difficulty constant', () => {
    expect(fixture.pow_difficulty).toBe('0xfffff80000000000')
  })

  for (const p of fixture.pow_vectors) {
    it(`powHash(${p.nonce}, ${p.hash_hex.slice(0, 8)}…)`, () => {
      expect(powHash(BigInt(p.nonce), hexToBytes(p.hash_hex, 32)).toString()).toBe(p.pow_hash)
    })
  }
})
